### PR TITLE
Chore: add support for Node 18; fix eslint issues

### PR DESCRIPTION
**Pull request by david-vaclavek**

### CODE REVIEW

**Comment by david-vaclavek** [comment]
Hello @ihmpavel.

Firstly, thank your for your [PR](https://github.com/localazy/strapi-plugin/pull/22) - we at Localazy appreciate it!

I had to do a couple more of minor changes to you PR; mainly related to plugin development issues (regarding your eslint package changes).

I opened another PR. Could you please double check the [Files changed](https://github.com/localazy/strapi-plugin/pull/24/files) whether it looks fine to you?

If so, I'll merge this PR.

**Comment by ihmpavel** [comment]
@david-vaclavek Hi, it looks good to me 🙌

**Comment by david-vaclavek** [comment]
@ihmpavel Okay then. Thank you for a quick review.

We'll merge this PR then (and link it to yours so there's  reason why we closed it).

@honzabilek4 Could you please do a one quick check and possibly merge it? :)

**Review by honzabilek4 — APPROVED** [review]

**Comment by honzabilek4** [comment]
Fine by me

**Pull request merged**
